#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touch,          sensorTouch)
#pragma config(Sensor, S3,     light,          sensorLightActive)
#pragma config(Sensor, S4,     sonar,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Copyright (c) 2014 Joshua Trahan. Licensed under the MIT License.
// For more information, visit github.com/r0but/tetrix-demo and read LICENSE.

/*
This is RobotC code. Despite the extension, trying to compile with a C
compiler will give errors. It is written for the LEGO NXT platform, but if you
want to try it on VEX or something give it a shot. I have no opportunity to use
a platform other than NXT and Arduino, and I don't use RobotC for my Arduino
projects, so I cannot provide any kind of support for anything but NXT.

The main task is at the bottom. Most of the motor controlling stuff is
in functions. The main loop is in the function mainLoop().

I haven't had much of a chance to test this code yet. It is functional,
but needs to be cleaned up, and probably has some bugs I haven't run into yet.

/****************************************************
*                                                   *
*    IMPORTANT: IN ROBOT CONFIG, NAME THE MOTORS    *
*       leftMotor AND rightMotor ACCORDINGLY.       *
*                                                   *
****************************************************/

#include "JoystickDriver.c"


void initializeRobot(){
  // Motors are not reversed by default. If your motor(s) are running backwards,
  // just change the corresponding motor to true OR tick "reversed" checkbox
  // for it in motor and sensor setup.
  bMotorReflected[rightMotor] = false;
  bMotorReflected[leftMotor] = false;
}
task main(){
  initializeRobot();
  waitForStart();
  while(1){
    motor[rightMotor] = joystick.joy1_y2;
    motor[leftMotor] = joystick.joy1_y1;
    wait1Msec(20);
  }
}
